version: '3.8'

services:
  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: rbx-danau-app
    restart: unless-stopped
    ports:
      - '${APP_PORT:-3000}:3000'
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_URL: ${DATABASE_URL}
      APP_NAME: ${APP_NAME:-Nest API}
      APP_PORT: ${APP_PORT:-3000}
      APP_VERSION: ${APP_VERSION:-1}
      APP_PREFIX: ${APP_PREFIX:-api}
    command: >
      sh -c "npx prisma migrate deploy &&
             node dist/main"
